//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sensit.TestSDK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceUnderTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeviceUnderTest()
        {
            this.DeviceComponents = new HashSet<DeviceComponent>();
        }
    
        public int EnvironmentID { get; set; }
    
        public virtual TestRun TestRun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceComponent> DeviceComponents { get; set; }
    }
}
