//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sensit.TestSDK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceComponent
    {
        public int DeviceUnderTestID { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public int EnvironmentID { get; set; }
    
        public virtual DeviceUnderTest DeviceUnderTest { get; set; }
    }
}
