//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sensit.TestSDK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int EquipmentID { get; set; }
        public string Name { get; set; }
        public string Quantity { get; set; }
        public int TestSuiteID { get; set; }
    
        public virtual TestSuite TestSuite { get; set; }
    }
}
