//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sensit.TestSDK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestStep
    {
        public int TestStepID { get; set; }
        public string Step { get; set; }
        public string ExpectedResult { get; set; }
        public int TestCaseID { get; set; }
    
        public virtual TestCase TestCase { get; set; }
        public virtual TestStepResult TestStepResult { get; set; }
    }
}
