//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sensit.TestSDK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestRun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestRun()
        {
            this.TestStepResults = new HashSet<TestStepResult>();
        }
    
        public int TestRunID { get; set; }
        public string Date { get; set; }
        public string Tester { get; set; }
        public int TestCaseID { get; set; }
        public string Notes { get; set; }
    
        public virtual TestCase TestCase { get; set; }
        public virtual TestCaseResult TestCaseResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestStepResult> TestStepResults { get; set; }
        public virtual DeviceUnderTest Environment { get; set; }
    }
}
