//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sensit.TestSDK.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestSTPToolContainer : DbContext
    {
        public TestSTPToolContainer()
            : base("name=TestSTPToolContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TestCase> TestCases { get; set; }
        public virtual DbSet<TestStep> TestSteps { get; set; }
        public virtual DbSet<TestStepResult> TestStepResults { get; set; }
        public virtual DbSet<TestRun> TestRuns { get; set; }
        public virtual DbSet<TestCaseResult> TestCaseResults { get; set; }
        public virtual DbSet<TestSuite> TestSuites { get; set; }
        public virtual DbSet<DeviceUnderTest> DeviceUnderTests { get; set; }
        public virtual DbSet<DeviceComponent> DeviceComponents { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
    }
}
