//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sensit.TestSDK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestStepResult
    {
        public int TestStepResultID { get; set; }
        public string ActualResult { get; set; }
        public string Status { get; set; }
        public int TestRunID { get; set; }
    
        public virtual TestStep TestStep { get; set; }
        public virtual TestRun TestRun { get; set; }
    }
}
